CREATE TABLE `position_statistics` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`position_id` integer NOT NULL,
	`first_monitored_at` integer DEFAULT (unixepoch()) NOT NULL,
	`last_price_check_at` integer,
	`time_in_range_ms` integer DEFAULT 0 NOT NULL,
	`time_out_of_range_ms` integer DEFAULT 0 NOT NULL,
	`current_oor_started_at` integer,
	`in_range` integer DEFAULT true NOT NULL,
	`last_rebalance_at` integer,
	`rebalances_count_lifetime` integer DEFAULT 0 NOT NULL,
	`rebalances_today` integer DEFAULT 0 NOT NULL,
	`daily_reset_at` integer DEFAULT (unixepoch()) NOT NULL,
	`crossbacks_90m` integer DEFAULT 0 NOT NULL,
	`last_crossback_at` integer,
	`current_mode` text DEFAULT 'TIGHT' NOT NULL,
	`mode_changed_at` integer DEFAULT (unixepoch()) NOT NULL,
	`active_width_pct` real DEFAULT 0.6 NOT NULL,
	`guard_width_pct` real DEFAULT 0.9 NOT NULL,
	`usd_value_on_open` real DEFAULT 0 NOT NULL,
	`total_claimed_usd` real DEFAULT 0 NOT NULL,
	`total_compounded_usd` real DEFAULT 0 NOT NULL,
	`total_fees_earned_usd` real DEFAULT 0 NOT NULL,
	`total_rebalance_cost_usd` real DEFAULT 0 NOT NULL,
	`last_rebalance_cost_usd` real,
	`net_pnl_usd` real DEFAULT 0 NOT NULL,
	`roi_percent` real,
	`time_in_range_percent` real,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch()) NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `position_statistics_position_id_unique` ON `position_statistics` (`position_id`);